### ISSUE TITLE
界面若干意见

### ISSUE THREAD

**Issue by xrkffgg** [woolson/npmer-page#10]
### 1 背景颜色
默认背景颜色使用 `#fafafa`，感觉有些太亮，可使用 `#f4f5f5`

调整背景颜色时，注意分页组件的颜色，可将其他分页框调整为白色。搜索按钮部分增加 `card`
### 2 滑块颜色
`.sort-group__item`和默认背景使用了相同背景色，不太容易区分，可使用`#eaeaea`

### 5 颜色选择
- 文字颜色点开面板后选择 clear 后，会默认为白色，但是框体中显示的为空，建议赋值为白色。
- 图标颜色点击 clear 后，会重置为黑色，建议更改为白色
- 两边背景颜色 clear 后，都为黑色，建议更改默认为 左黑 右绿

**Comment by woolson** [comment]
后面更新尽量解决这些问题，非常感谢🤙🤙🤙
