### ISSUE TITLE
建议：限制下图标大小

### ISSUE THREAD

**Issue by lxhyl** [woolson/npmer-page#9]
![IMG_20191227_022740](https://user-images.githubusercontent.com/41041503/71486275-827dd200-2850-11ea-82bd-2fff76651531.jpg)

**Comment by lxhyl** [comment]
另外，第一次看到长这样的代码，从大佬这儿知道了pug,这东西好用不好用呀？

**Comment by woolson** [comment]
- 图标有缩放的，正常使用图标尺寸应该没问题；
- PUG的话真香，一直都用（eslint-plugin-vue不支持PUG）；
